using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace API.Entities
{
    public class Message
    {
        //each meesage require Id which will be generated by db
        public int Id { get; set; }

        //we need track sender id
        public int SenderId { get; set; }
        //messager username 
        public string SenderUserName { get; set; }
        //relationship of property to sender
        public AppUser Sender {get; set;}
        //recipient id
        public int RecipientId { get; set; }
         //messager reciver username
        public string RecipientUserName { get; set; }
        //relationship of property to recipient
        public AppUser Recipient {get; set;}
        //message content
        public string Content { get; set; }
        //time message is read 
        public DateTime? DateRead {get; set;} //we make this optional if the message has not be read
        //time the message is send
        public DateTime DateMessageSent {get; set;} = DateTime.Now; //we make this optional if the message has not be read
         //check message sender is deleted
        public bool SendDelete { get; set; }
         //check message recipient is deleted
        public bool RecipientDelete { get; set; }


    }
}